{% set version = "1.12.1" %}
{% set build_number = "0" %}

package:
  name: ninja-suite
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a

build:
  number: {{ build_number }}

outputs:
  - name: ninja-base
    script: build-ninja.sh  # [unix]
    script: bld-ninja.bat   # [win]
    build:
      ignore_run_exports:
        - vc
    requirements:
      build:
        - {{ compiler("cxx") }}
        - cmake
        - make  # [not win]
        - gtest
    test:
      commands:
        - ninja --version

  - name: ninja
    requirements:
      run:
        - {{ pin_subpackage('ninja-base', exact=True) }}
        - python

about:
  home: https://ninja-build.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed
  dev_url: https://github.com/ninja-build/ninja
  doc_url: https://ninja-build.org/manual.html
  doc_source_url: https://github.com/ninja-build/ninja/tree/master/doc

extra:
  recipe-maintainers:
    - frol
