travis:
  secure:
    BINSTAR_TOKEN: soFpbT2t9O5J2neh/+N+Z7hiQoL8y8HpWLyJLZkLac4fVR6ez4/0t2DFaNjiTGl8bePu3tvf33FE1VuBV7m+czqrqjsEot8IMNEFTMU/8N077zdaplpxcth6YsXvzlNNQH/Fw/nIhrOkQLJHKDOh1bDO11GsIviFumM13Ycyku1LEIhUMJsf9AvmbK2ssw98UHVNjFCQ7eZCkDKRCqJ9et8xHEfbmASH/isWuRtVIPp/l5GLCgttdNiRqh9A2Gq4HEkdnlK/0lgdB9Lec3T8nd6Mro5URHkE1aJNwAL7XnvtbtYKo43NLNmhjwTGy7TQP30p4EQ6q9V+v/Aps29jDIXwbCVlMdTfFqzDuOdTcNloCd/mKxRV+SLhD1B4atZyElaINnaSIMkWpop5uh/0Fq8pjaGel1/TNAEA20bBTwx3Ra0m/OoKA4YRYHMQXLi+dS9zn+IkPJBh0IsFKyNsw7N1fZF902bowgk25sV4EjpO4E9lKotdnsGF99LFTpaN73j1UPCZ7XuP0EKBVy6N9xnpMk3lJVT5sYRZLllEA2i1SisBYNaGlxr65YsRoLOEAN2NECrkcE9KccqpxH0ugQAC+Ed5ff9zREF3PArdTFEO0uLRo+/nFYpWuuYMRJv4VQEk0jUUYU0CLgzKEXNRG0T/Ky7qPQEoCIEctM5Ij2I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
